name: ammp-connect
version: '1.5'
summary: Set up SSH tunnel to AMMP gateway et.ammp.io
description: |
  This snap sets up an SSH tunnel and a WireGuard connection to the AMMP gateway, to be used for
  reverse access to edge devices.

grade: stable
confinement: strict

base: core22

architectures:
  - build-on: armhf
  - build-on: arm64

apps:
  sshtunnel:
    command: bin/tunnel.sh
    daemon: simple
    plugs: [network]
  wg-svc:
    command: bin/wg_svc_start.sh
    stop-command: bin/wg_svc_stop.sh
    daemon: oneshot
    plugs: [network, network-bind, network-observe, network-control]
    environment:
      WG_ENDPOINT_RESOLUTION_RETRIES: infinity
    install-mode: disable
  wg:
    command: usr/bin/wg
    plugs: [network, network-bind, network-control]
  wg-quick:
    command: usr/bin/wg-quick
    plugs: [network-control]
  wireguard-go:
    command: usr/bin/wireguard-go
    plugs: [network, network-bind, network-control]

parts:
  sshtunnel:
    plugin: dump
    source: sshtunnel/
    override-build: |
      chmod 600 id_ed25519_remote
      craftctl default
    stage-packages:
      - openssh-client
      - autossh
  wg-scripts:
    plugin: dump
    source: wg-scripts/
  wireguard-tools:
    plugin: make
    source-type: git
    source: https://git.zx2c4.com/wireguard-tools
    source-tag: v1.0.20210914
    source-subdir: src/
    build-packages:
      - libmnl-dev
      - build-essential
    make-parameters:
      - WITH_WGQUICK=yes
      - RUNSTATEDIR=/run/snap.ammp-connect
  wireguard-go:
    plugin: make
    source-type: git
    source: https://git.zx2c4.com/wireguard-go
    source-branch: 0.0.20220316
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/wg_socket_dir.patch
    build-snaps: [go]

layout:
  /etc/wireguard:
    bind: $SNAP_COMMON
